export const ADD_TOPIC = 'ADD_TOPIC';
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const UPVOTE_TOPIC = 'UPVOTE_TOPIC';
export const DOWNVOTE_TOPIC = 'DOWNVOTE_TOPIC';
export const RECEIVE_UPDATED_TOPIC = 'RECEIVE_UPDATED_TOPIC';
export const RECEIVE_NEW_TOPIC = 'RECEIVE_NEW_TOPIC';
